on:
  google_form:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          answer: ${{ toJSON(on.google_form.outputs.answers_map) }}
        run: |
          echo answer: $answer
      - name: Send telegram message - hackernews
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
                  Today's Form Submission comes from GOogle Form :
                 ${{ toJSON(on.google_form.outputs.answers_map) }}

