name: Send telegram message - hackernews site
on:
  rss:
    url: 
      - https://hnrss.org/newest?count=5
      - https://www.buzzfeed.com/tvandmovies.xml
      - https://www.buzzfeed.com/category/celebrity.xml
      - ${{secrets.TP_URL}}
    config:
      limit: 10
jobs:
  telegram:
    name: Send telegram message - hackernews 
    runs-on: ubuntu-latest
    steps:
      - name: url short generator bit.ly
        id: urlshortgen
        uses: kok-xiong/bitly-shortener-action@master
        with:
          bitlyToken: ${{ secrets.BITLY_TOKEN }}
          longURL: ${{on.rss.outputs.link}}

      - name: Print Outputs
        env:
           title: ${{on.rss.outputs.title}}
           contentSnippet: ${{on.rss.outputs.contentSnippet}}
           link: ${{on.rss.outputs.link}}
           short: ${{steps.urlshortgen.outputs.shortURL}}
        run: |
           echo title: $title
           echo contentSnippet: $contentSnippet
           echo link: $link
           echo short: $short

      - name: Print Output link and shortURL
        run: |
            echo RSS Output link
            echo ${{on.rss.outputs.link}}
            echo
            echo url short gen shortURL
            echo ${{steps.urlshortgen.outputs.shortURL}}
            echo
      - name: Send telegram message - hackernews
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
                  Today's news :
                  ${{steps.urlshortgen.outputs.shortURL}}
