name: Send a telegram message based on periodic polling on hackernews site
on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
    config:
      outputsMode: combine
jobs:
  telegram:
    name: Send telegram message for hackernews portal
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message for hackernews portal
        uses: appleboy/telegram-action@v0.0.8
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ on.rss.outputs.link }} ${{ on.rss.outputs.title }} <<<${{ on.rss.outputs.contentSnippet }}>>>
