name: Send telegram message - hackernews site
on:
  rss:
    url: https://hnrss.org/newest?count=2
jobs:
  telegram:
    name: Send telegram message - hackernews 
    runs-on: ubuntu-latest
    steps:
      - name: url short generator bit.ly
        id: urlshortgen
        uses: kok-xiong/bitly-shortener-action@master
        with:
          bitlyToken: ${{ secrets.BITLY_TOKEN }}
          longURL: ${{on.rss.outputs.link}}

      - name: Send telegram message - hackernews
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{steps.urlshortgen.outputs.shortURL}}
