name: Send telegram message - hackernews site
on:
  rss:
    url: https://hnrss.org/newest?count=5
jobs:
  telegram:
    name: Send telegram message - hackernews 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: url short generator bit.ly
        id: urlshortgen
        uses: kok-xiong/bitly-shortener-action@master
        with:
          bitlyToken: ${{ secrets.BITLY_TOKEN }}
          longURL: ${{on.rss.outputs.link}} || https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      - name: Send telegram message - hackernews
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{steps.urlshortgen.outputs.shortURL}}
