on:
  email:
    imap:
      host: imap.zoho.in
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: Notify Email-Subject to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram email message to telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: tests/gophercolor.png
          message: |
                   You've got a Email
                   ${{(on.email.outputs.subject)}} and 
                   ${{(on.email.outputs.text)}}
                   and details of Object :
                   ${{(on.email.outputs)}} 
