on:
  email:
    imap:
      host: imap.zoho.in
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message - hackernews
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
                  You've got a Email
                  ${{(on.email.outputs.subject)}}
